### ISSUE TITLE
JavaScript read only error. 

### ISSUE THREAD

**Issue by mygsunny** [StewM/streamlabs-donations-printer#5]
Hey, I'm trying to get this to work on macos after I finish running the builder and run the program I get this error. can you point me in the right direction?

also on the side note are you able to add print for youtube subscription?

A JavaScript error occurred in the main process
Uncaught Exception:
Error: EROFS: read-only file system, mkdir './pdfs'
    at Object.mkdirSync (fs.js:764:3)
    at Module.<anonymous> (/Users/sunny/Downloads/streamlabs-donations-printer-master/build/mac/Streamlabs Donations Printer.app/Contents/Resources/app.asar/dist/electron/main.js:1:32454)
    at n (/Users/sunny/Downloads/streamlabs-donations-printer-master/build/mac/Streamlabs Donations Printer.app/Contents/Resources/app.asar/dist/electron/main.js:1:115)
    at /Users/sunny/Downloads/streamlabs-donations-printer-master/build/mac/Streamlabs Donations Printer.app/Contents/Resources/app.asar/dist/electron/main.js:1:923
    at Object.<anonymous> (/Users/sunny/Downloads/streamlabs-donations-printer-master/build/mac/Streamlabs Donations Printer.app/Contents/Resources/app.asar/dist/electron/main.js:1:933)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)

![Screen Shot 2021-05-31 at 6 24 56 AM](https://user-images.githubusercontent.com/84654934/120179748-f60bd780-c1d8-11eb-8f60-d368cd6dbc1e.png)

**Comment by mygsunny** [comment]
seems like the file system was written for windows, I was able to change the pdfs and images folder to a different location and it seems to work.
